settings:
  default_chance: 5.0 # шанс если у игрока нет ни одного права на новый шанс
  maxSpawnerLevel: 35
  maxLootItemsLimitPerLevel: 256
  maxExpLimitPerLevel: 20000
  spawnLootTimer: 60 # 60 секунд
  minLootTimer: 25
  reducedCoeff: 1
  spawner_name: "&aВиртуальный Спавнер"
  spawner_lore:
    - '&7Тип: &a%mob_type%'
    - '&7Уровень: &a%spawner_level%'
    - '&7Добыт: &a%player%'
  loot_item_lore:
    - " "
    - "&b Нажмите чтобы забрать!"
    - " "
  default_holo_height: 3.5
  default_holo:
    - Material.SPAWNER
    - '&7Спавнер &a%mob_type% &8[&7%level%&8] &7ур.'
    - '&7Владелец: &a%owner%'
    - ''
    - '&7Хранилище: &a%items%&8/&7%max_items%'
    - '&7Опыт: &a%exp%&8/&7%max_exp%'
  fulled_holo_height: 3.5
  fulled_holo:
    - Material.SPAWNER
    - '&7Спавнер &a%mob_type% &8[&7%level%&8] &7ур.'
    - '&7Владелец: &a%owner%'
    - ''
    - '&7Хранилище: &c%items%&8/&7%max_items%'
    - '&7Опыт: &c%exp%&8/&7%max_exp%'
messages: # поставьте в начале сообщения "NONE" чтобы отключить само сообщение для показа игроку
  # поставьте в начале "HOTBAR" чтобы сообщения отобразилось игроку в его хотбар
  reload:
    - "&aВы успешно перезагрузили плагин!"
  noPermission:
    - "&cУ вас нет прав на использование команды!"
  spawnerBroken:
    - " "
    - "&6☠️ &8┃ &cНе удалось &8добыть спавнер.."
    - " "
    - "TITLE &fСпавнер {S} &cНеудача..."
  spawnerReceived:
    - " "
    - "&6☠️ &8┃ &aСпавнер добыт!"
    - " "
    - - "TITLE &fСпавнер {S} &aУдача!"
  hasLootInside:
    - " "
    - "&6☠️ &8┃ &cСпавнер нельзя поломать пока в нём есть лут!"
    - " "
  collectExp:
    - " "
    - "&6☠️ &8┃ &aВы забрали x{0} опыта из спавнера!"
    - " "
  noExp:
    - " "
    - "&6☠️ &8┃ &cВ спавнере нет опыта для сбора!"
    - " "
  noPages:
    - " "
    - "&6☠️ &8┃ &cДальше листать нельзя!"
    - " "
  clickOnNatureSpawner:
    - "HOTBAR &7Шанс добычи: &a{0}%"
  youNotOwner:
    - " "
    - "&6☠️ &8┃ &cВы не владелец этого спавнера!"
    - " "
  playerIsOffline:
    - "&6☠️ &8┃ &cИгрок {0} не в сети!"
  givingSpawner:
    - "&6☠️ &8┃ &aВы выдали игроку {0} спавнер с мобом {1} уровня {2}!"
  collectAllItems:
    - "&6☠️ &8┃ &aВы забрали все предметы из хранилища!"
  noItems:
    - "&6☠️ &8┃ &cВ хранилище нет предметов!"
  levelUp:
    - "&6☠️ &8┃ &cВы успешно повысили уровень спавнера с {0} до {1} &8(+{2})!"
  breakInRegion:
    - "&6☠️ &8┃ &cСпавнер нельзя сломать, так как он в чужом регионе!"